archlinux:
  children:
    group_homelab:
      hosts:
        bypass:
        cluster:
        dns:
        downloader:
        exit-node:
        grafana:
        lxd:
        media:
        minio:
        mysql:
        postgresql:
        powerdns:
        proxy:
        redis:
        runner:
        test:
        work:

    group_onion:
      hosts:
        groot:
        ironman:
        spiderman:

vps:
  children:
    group_bypass:
      hosts:
        hk01-gcp:
        hk02-gcp:
        jp01-oracle:
        jp02-oracle:
        sg01-gcp:
        sg02-gcp:
        tw01-gcp:
        tw02-gcp:
        us01-gcp:
        us02-gcp:

all:
  vars:
    ansible_ssh_user: shikun
