archlinux:
  children:
    group_homelab:
      hosts:
        bypass:
        cluster:
        dns:
        downloader:
        exit-node:
        grafana:
        lxd:
        media:
        minio:
        mysql:
        postgresql:
        powerdns:
        proxy:
        redis:
        runner:
        test:
        work:

    group_onion:
      hosts:
        galactus:
        groot:
        ironman:
        spiderman:

vps:
  children:
    group_bypass:
      hosts:
        jp01-oracle:
        jp02-oracle:
        sg-gcp:
        hk-gcp:
        tw-gcp:

all:
  vars:
    ansible_ssh_user: shikun
