archlinux:
  hosts:
    bypass:
    cluster:
    dns:
    downloader:
    exit-node:
    grafana:
    lxd:
    media:
    minio:
    mysql:
    postgresql:
    powerdns:
    proxy:
    redis:
    runner:
    test:
    work:

vps:
  children:
    vps_ubuntu:
      hosts:
        aws-sg:
        hk01-gcp:
        hk02-gcp:
        jp01-oracle:
        jp02-oracle:
        sg01-gcp:
        sg02-gcp:
        us01-gcp:
        us02-gcp:

all:
  vars:
    ansible_ssh_user: shikun
