#! /usr/bin/env bash

# homebrew
brew bundle --global

mkdir Developer

# python
PYTHON_VERSION=$(cat $HOME/.pyenv/version)
pyenv install $PYTHON_VERSION

# rust
rustup-init

# node
NODE_VERSION=$(cat $HOME/.nvmrc)
fnm use --install-if-missing $NODE_VERSION
corepack enable && corepack prepare pnpm@latest --activate

# flutter
git clone git@github.com:flutter/flutter.git Developer/flutter

# shell
chsh -s $(which fish) $(whoami)
curl -sL https://git.io/fisher | source
fisher update
