require('impatient')
require('plug').setup()
require('core.opt').setup()
require('core.tool').setup()
require('core.keymap').setup()
require('core.au').setup()
require('ide.lsp').setup()
require('ide.cmp').setup()
