require('plug').setup()
require('core.opt').setup()
require('core.ui').setup()
require('core.tool').setup()
require('core.keymap').setup()
require('core.au').setup()
require('core.ft').setup()
require('ide').setup()
